color: sky
fieldLayouts:
  b57a33f2-eaed-4c46-ab6f-94a38cbdcca1:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2024-11-22T10:18:04+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 07e37d91-ebf2-458f-be6c-3b427693188d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2024-11-22T10:20:10+00:00'
            elementCondition: null
            fieldUid: e2e222ba-6107-4ebe-ba6f-c26cc3a40dd8 # Plain Text
            handle: subtext
            includeInCards: false
            instructions: null
            label: Subtext
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: db3870dc-7ecf-455a-bea9-290f031204f4
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9e508cef-adc3-45d3-83e9-330863082d9a
        userCondition: null
handle: locations
hasTitleField: true
icon: location-dot
name: Locations
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: ''
titleTranslationKeyFormat: null
titleTranslationMethod: site
